Makefile, TODO, bash-completion/Makefile, bash-completion/fdectl, fde.sh, man/Makefile, man/fdectl.h2m
I believe the title is self-explanatory, and this requires a modification to the spec file.
```
--- fde-tools.spec      (revision 15)
+++ fde-tools.spec      (working copy)
@@ -30,6 +30,7 @@
BuildRequires:  openssl >= 0.9.8
BuildRequires:  tpm2-0-tss-devel
BuildRequires:  dracut
+BuildRequires:  help2man
Requires:      pcr-oracle >= 0.4.2
Requires:      cryptsetup
@@ -88,6 +89,9 @@
%{_fillupdir}/sysconfig.*
%{_datadir}/fde
%{_unitdir}/fde-tpm-enroll.service
+%dir %{_datadir}/bash-completion/completions/
+%{_mandir}/man8/fdectl.8.*
+%{_datadir}/bash-completion/completions/fdectl
```
=> Add man page and bash completion support.

share/commands/tpm-authorize, share/commands/tpm-enable, share/grub2, share/systemd-boot, share/tpm
With TPM 2.0 Key File support in grub2, we don't need to specify the details, such as the PCR bank algorithm and numbers, to construct the policy for key unsealing. All the necessary information is included the key file. Besides, grub2 can use the same grub.cfg for SRK mode and Authorized Policy mode, so several additional grub2 variables can be removed.
This commit tweaks the pcr-oracle parameters for 'seal-secret' and 'sign' to adopt TPM 2.0 Key File format. When sealing the secret with 'seal-secret', an additional parameter '--key-format tpm2.0' is added to save the sealed key in TPM 2.0 Key File format. When signing the policy with 'sign' + '--key-format tpm2.0', pcr-oracle fetches the orignal sealed key file, adds the newly signed policy and then saves the new key file in ESP for …
=> Switch to TPM 2.0 Key File for grub2

Makefile, share/commands/tpm-activate, share/commands/tpm-disable, share/commands/tpm-enable, share/luks, sysconfig.fde
The 'tpm-disable' command verifies the recovery passphrase first and then removes the TPM key unsealing commands from grub.cfg. All the key files, the user private key and the sealed key, are kept in /etc/fde so that the user can enable TPM key unsealing later.
To avoid adding the TPM key unsealing commands back to grub.cfg on every boot by fde-tpm-enroll.service, a new command, tpm-activate, is introduced to check FDE_TPM_ENABLE in /etc/sysconfig/fde-tools and skip the key enablement if the variable is not 'yes'.
=> Implement 'tpm-disable' command

.gitignore, Makefile, cryptsetup/cryptsetup-token-grub-tpm2.c, cryptsetup/libcryptsetup-token.sym, fde.sh, firstboot/fde, share/commands/add-secondary-password, share/commands/regenerate-key, share/commands/tpm-disable, share/commands/tpm-wipe, share/grub2, share/luks, share/systemd-boot, src/fdectl-grub-tpm2.c, src/nls.h
A new LUKS2 token, grub-tpm2, is created to group the keyslots created for the sealed random key. With the help of the new token, two new commands are added to fdectl: tpm-wipe and regenerate-key. The first command wipes all the keyslots assigned to grub-tpm2 tokens, and the second command generates a new random key, seal the key, and remove the old random key.
=> LUKS2 keyslot management with the grub-tpm2 token

share/tpm
Both firstboot/fde and fdectl clean up the temp directory on exit. Calling fde_clean_tempdir in tpm_test would unset FDE_TEMP_DIR and make fde_make_tempdir fail afterward.
=> Don't clean up the temp directory in tpm_test

firstboot/fde
Aliases are not expanded in non-interactive mode by default, so those function aliases defined in the 'grub2' script won't work for firstboot. Manually define the bootloader specific functions in firstboot/fde to avoid the potential 'command not found' error.
=> firstboot/fde: use functions as the aliases for bootloader functions

firstboot/fde
To make sure the initrd is always recreated, specify '--force' to dracut.
=> firstboot/fde: forcefully invoke dracut

fde.sh, firstboot/fde, share/util
Update the firstboot script to enable authorized policy by default.
=> Enable authorized policy in the firstboot script

share/commands/add-secondary-key, share/tpm
The return value of tpm_create_authorized_policy was not checked, and this may ignore the failure from the underlying functions. Besides, the return value of some pcr-oracle commands were not correctly handled. Fix those cases to make fdectl exit right after the failure of the pcr-oracle commands.
=> Check failure of authorized policy creation

firstboot/fde, share/ui/dialog
- Redirect the firstboot messages to journald instead of a standalone log file.
- Update /boot/grub2/grub.cfg at the end of firstboot to reflect the LUKS key change
=> Print firstboot messages to journald and update grub config

Makefile
The 'cryptsetup' directory was missing when making the tarball.
=> Add 'cryptsetup' to 'make dist'

Makefile
The version number in fde.sh was accidentally hardcored as 0.1.
=> Fix the version in fde.sh

firstboot/fde
'transactional-update grub.cfg' stores the updated grub.cfg in the next snapshot. To avoid the next transactional-update uses the wrong snapshot, invoke 'transactional-update apply' to switch to the snapshot with the new grub.cfg change.
=> firstboot: apply the grub.cfg change

share/commands/add-secondary-key
The secondary password is only specific to the firstboot and it's the responsibility of the installer to invoke 'fdectl add-secondary-password'. Since Agama is preparing to add the command, we can remove the workaround for good.
=> add-secondary-key: remove the generation of the secondary password

README.md, fde.sh, share/commands/add-secondary-key, share/luks, sysconfig.fde
For the root partition in a LVM VG, there may be multiple LUKS PVs. In that case, we have to handle all those LUKS PVs at the same time. This patchset detects all the underlying LUKS devices of the root partition instead of only one device. A new variable, FDE_DEVS, is also introduced to list all devices to be managed by fdectl and retire FDE_EXTRA_DEVS since the user may be confused by the definition of 'devices other than the root partition'.
=> Support the root partition with multiple underlying LUKS devices

fde.sh
As long as `fdectl tpm-authorize' is used quite often in bootloader update to update the predicted pcr value and signature for authorized policy, it is convenient to have it listed in the help command output so that it is shown in the man page and also the bash completion.
=> Add help output for the command tpm-authorize

firstboot/fde
- The firstboot script may be used in the system other than ALP.
- Disable the non-functional ccid option
=> Fix naming and disable ccid

share/tpm
Modify tpm_test() to use the tpm2.0 key format for sealing and unsealing to be compatible with the newer pcr-oracle.
=> tpm: fix tpm-present with the newer pcr-oracle

firstboot/fde
Without choosing the "Pass phrase" option, the default VM password will remain after firstboot. To ensure the default password is gone for good, make "Pass phrase" mandatory.
=> firstboot: make "Pass phrase" mandatory

firstboot/fde
Currently, the firstboot script skipped the disk reencryption when UEFI Secure Boot is off, and the default disk password was kept unnoticed. To avoid such situation, this commit moves the UEFI Secure Boot check to fde_choose_protection() and removes the TPM2 entry when it is off, so that the user can at least change the disk password.
=> firstboot: disable FDE/TPM2 when secure boot is off

firstboot/fde
The key file path in crypttab is not necessary after the system completes re-encryption since it becomes only a reference for GRUB2 when generating the synthesized initrd to forward the disk key. Specifying a key file path in the directory other than '/' could introduce the extra dependency when unmounting the LUKS partitions and lead to the unexpected error/warning. Unfortunately, the root partition is read-only in SL-Micro, so KIWI has to create the key file in "/root".
To avoid the unexpected error/warning, this commit replace the key file path with "/.virtual-root.key" after the firstboot script removes the default key file. This makes dracut/systemd believe that the key file is in the root partition, so there is no extra dependency when unmounting the LUKS partitions.
The initrd also …
=> firstboot: replace the key file path in crypttab

firstboot/fde
There are 3 missing bootloader functions needed by the 'tpm' script:
- bootloader_platform_parameters
- bootloader_rsa_sizes
- bootloader_stop_event
Add those functions in the firstboot script to avoid the potential "command not found" error.
=> firstboot: add more alias bootloader functions

firstboot/fde
KIWI inserts a dracut conf to include the default key file into initrd. Since the key file is not used after reencryption, the dracut conf should be removed to avoid the potential error from dracut.
=> firstboot: remove the dracut conf for the key file

share/tpm
The 'snapshot' directory is created by pcr-oracle so it doesn't exist until the command finish its work.
Redirect the output of pcr-oracle, i.e. the predicted PCR, to the temporary directory first and move it into the snapshot directory later.
=> tpm: Fix the file path for the predicted PCR

share/tpm
When feeding the output of pcr-oracle to fde_trace, the whole output strings have to be guarded by the quotation marks. Otherwise, every word would be treated as an argument to 'echo' and the newlines would be ignored.
=> tpm: Fix the output format of tpm-inspect

share/uefi
Some boot entries are generated by the firmware automatically, and those boot entries load the default boot path: "\EFI\BOOT\boot*.efi". Tweak uefi_get_current_loader() to use the default EFI boot path as the fallback.
=> uefi: use the default boot path if no EFI FILE path
